version: '2.1'
services:
  core:
    build: puzzle-core
    environment:
      EMBEDDED_MONGO_ARTIFACTS: /opt/app/.embedmongo
    ports:
      - 8080:8080
    volumes:
      - .embedmongo:/opt/app/.embedmongo
